language: android
sudo: required
jdk: oraclejdk8

dist: trusty
env:
  global:
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - EMU_NAME=test
    - EMU_API_LEVEL=23
    - EMU_ABI=armeabi-v7a
#    - EMU_ABI=x86

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMU_API_LEVEL
    - extra-android-support
    - sys-img-$EMU_ABI-google_apis-$EMU_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - echo yes | sdkmanager "build-tools;28.0.3"
  - echo yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "platforms;android-$EMU_API_LEVEL"

before_script:
  - echo no | android create avd --force -n $EMU_NAME -t android-$EMU_API_LEVEL --abi google_apis/$EMU_ABI
  - emulator -avd $EMU_NAME -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - ./gradlew connectedCheck
  - ./gradlew test
  - ./gradlew testDebugUnitTest
  - ./gradlew connectedDebugAndroidTest